### ISSUE TITLE
Trivial issue during running worker with PrintLogger

### ISSUE THREAD

**Issue by gurkanguran** [NeuroChainAi/worker-node#1]
When i initialized the worker with server.exe, I saw the following error:

AttributeError: 'PrintLogger' object has no attribute 'flush'

However, the worker continued to run successfully after that. But still I wanted to create an issue as it might be something to fix.

![image](https://github.com/NeuroChainAi/worker-node/assets/54795879/aa81df12-18bd-402b-bbd9-945d45b2f0f6)

Machine: Windows 11 
Graphic card: RTX 2070

Update: Some users' workers did not start successfully due to the same error.

**Comment by NeuroChainAi** [comment]
This is related to Windows compatibility. Warning caused by system logger. We plan to rectify it with the next release of worker node.
